version: '3'
services:
  admin:
    image: doopai/litemall
    build: litemall
    restart: unless-stopped
    ports:
      - "8081:8080"
    command: /opt/litemall/admin.jar
    depends_on:
      - db
    volumes:
      - ./litemall/log:/var/log
      - ./litemall/config:/opt/litemall/config

  apollo:
    image: doopai/litemall
    restart: unless-stopped
    ports:
      - "8082:8080"
    command: /opt/litemall/apollo.jar
    depends_on:
      - admin
    volumes:
      - ./litemall/log:/var/log
      - ./litemall/config:/opt/litemall/config

  horizon:
    image: doopai/litemall-horizon
    build: 
      context: litemall-horizon
    restart: unless-stopped
    ports:
      - "8083:8000"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: litemall123456
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/sql/litemall.sql:/docker-entrypoint-initdb.d/litemall.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
